apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-namespace
spec:
  template:
    spec:
      containers:
      - name: myapp-container
        image: nginx:1.23
